version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      #ALLOW_EMPTY_PASSWORD: yes
      REDIS_PASSWORD: redis
      REDIS_PORT_NUMBER: 6379
    ports:
      - "6379:6379"
    command: /opt/bitnami/scripts/redis/run.sh --maxmemory 100mb